RH_27_Make_Endpoint_for_FAQ_and_FAQ_table
7smurfs/rehub-backend pull request #8
Opened 2023-10-28 22:50 UTC by antonVivoda

Created FAQ table and Endpoint for FAQ

2023-10-29 14:01 UTC, begjosip commented
In faq schema, question and answer can be set to text instead of varchar 255 due to faster fetching and will solve longer questions and answers problem. Format all classes with ctrl alt l. In GetMapping remove ADMIN in logging. And in PostMapping don't map to Faq direct. Create class FaqRequest, then in service from request create Faq.

2023-10-29 21:25 UTC, antonVivoda commented
In faq schema question and answer type changed to text, all classes have been formatted, removed ADMIN in GetMapping logging, created FaqRequest and updated PostMapping

2023-10-29 22:03 UTC, begjosip requested changes

2023-10-29 22:16 UTC, antonVivoda commented
added @validated in PostMapping function, removed id from FaqRequest, removed setting id in FaqService class

2023-10-30 07:00 UTC, begjosip approved these changes

2023-10-30 09:42 UTC, merged